### ISSUE TITLE
urmom

### ISSUE THREAD

**Issue by michaelV04** [Maxnboy/Textadventure#1]

**Comment by michaelV04** [comment]
lol

**Comment by Maxnboy** [comment]
danke dir diggi kuss geht raus brudi

**Comment by Maxnboy** [comment]
bitch

**Comment by michaelV04** [comment]
Hey thank for your answer but oi m8 do y have a bowwoo of waaaa

**Comment by Maxnboy** [comment]
I do fancy some chips currently

**Comment by michaelV04** [comment]
oi cunt you want to get canceled on twitter you twack

**Comment by simk12** [comment]
hellöööö, iatz bin a do

**Comment by michaelV04** [comment]
maul

**Comment by Maxnboy** [comment]
blocked. reported. cancelled. <3

**Comment by simk12** [comment]
au du bitch

**Comment by Maxnboy** [comment]
oki mommy

**Comment by michaelV04** [comment]
oi m8 but ur project kinda looking like your life empty dud

**Comment by Maxnboy** [comment]
thank you! I love getting useful critisism, much appreciated mate <3

**Comment by Maxnboy** [comment]
critisim helps me fuck ur mom

**Comment by michaelV04** [comment]
more like critisim help you getting fucked m8

**Comment by simk12** [comment]
.

**Comment by michaelV04** [comment]
Your project suck cunt so stfu im outa here prof

**Comment by Maxnboy** [comment]
oki <3 thanks again
